[sync plan] descriptions and cron expressions (and some doc fixes)
HanseMerkur/terraform-provider-foreman pull request #30
Opened 2021-05-14 12:10 UTC by Schluggi

I fixed some docs and added support for descriptions and cron expressions to katello sync plans.

2021-05-18 12:38 UTC, lhw requested changes
Thank you for your contribution. I commented on some indentation problems and mentioned a solution for the documentation problems you noticed.

2021-05-18 12:38 UTC, lhw commented on docs/data-sources/foreman_computeprofile.md
> +  name = "2-Medium"
All docs are autogenerated using the autodoc util. So changes to documentation should be done by editing the description in the resource/datasource files instead. Like the first change in your PR which is generated by [data_source_foreman_computeprofile.go](https://github.com/HanseMerkur/terraform-provider-foreman/blob/master/foreman/data_source_foreman_computeprofile.go#L25) with a `%s` format string pointing to nothing.
I think the same goes for most of the doc changes.

2021-05-18 12:38 UTC, lhw commented on foreman/data_source_foreman_computeprofile.go
> +		    	),
What gofmt'er were you using? Or did you accidentally de-indent these line?

2021-05-18 12:38 UTC, lhw commented on foreman/provider.go
> +            "foreman_katello_product":            resourceForemanKatelloProduct(),
Same de-indentation here

2021-05-18 12:38 UTC, lhw commented on foreman/resource_foreman_katello_product.go
> +		},
I recommend running gofmt against your files. That will automatically fix your indentation problems

2021-05-18 12:38 UTC, lhw commented on foreman/resource_foreman_katello_sync_plan.go
> +			},
Here as well

2021-05-18 12:38 UTC, lhw commented on foreman/resource_foreman_katello_sync_plan.go
> +    syncPlan.CronExpression = d.Get("cron_expression").(string)
and here

2021-05-18 13:34 UTC, Schluggi commented
> 
> 
> Thank you for your contribution. I commented on some indentation problems and mentioned a solution for the documentation problems you noticed.

Thank you. That is my first go project and also my first pull request ever. So... sorry for the problems.
The indentation-problem is a classic "ide replaces tabs with spaces"-issue (what is helpful in the python world). 

I'll fix it..

2021-05-18 13:44 UTC, Schluggi commented on docs/data-sources/foreman_computeprofile.md
> +  name = "2-Medium"
I've change the description and than generated the docs. So the docs should't be part of the pr?

2021-05-18 13:45 UTC, Schluggi commented on foreman/data_source_foreman_computeprofile.go
> +		    	),
No gofmt'er at all (until now), but in my ide i can't see the difference between spaces and tabs. I'll use gofmt for further PRs.

2021-05-18 15:20 UTC, lhw commented on docs/data-sources/foreman_computeprofile.md
> +  name = "2-Medium"
We require the documentation to be part of the commit due to how the official terraform registry pulls the markdown files. So it needs to be added with each change. If it could be some other branch we could just auto generate it on every push. You can find the info on how to generate the documentation automatically in the [README](https://github.com/HanseMerkur/terraform-provider-foreman#documentation).

2021-05-19 12:49 UTC, lhw approved these changes

2021-05-19 12:54 UTC, merged